server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**
        - id: provider-service
          uri: lb://provider-service
          predicates:
            - Path=/api/providers/**
        - id: service-catalog-service
          uri: lb://service-catalog-service
          predicates:
            - Path=/api/services/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
